### ISSUE TITLE
toplev reports 28 cores on 20 core cpu 

### ISSUE THREAD

**Issue by sandlbn** [andikleen/pmu-tools#127]
On the 2 socket Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz and kernel Linux xxxx 4.15.0-32-generic #35-Ubuntu SMP after running toplev with below configuration. 

```
./toplev.py --all --power -I 1000 -x, -o dataset.csv  sleep 30
```

I get data with the following errors: 
- cores from 5-7,  10-12, 15-18 were reporter with core_id + 3. E.g. Measurements from core 11 were reported as 17. 

Then I took a server with Broadwell architecture Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz and get the same error. 

Any idea what is happening? I'm using the latest pmu-tools from the github.

**Comment by andikleen** [comment]
toplev uses the core numbers that the OS reports. The OS takes it from the apic id, which comes from the BIOS and ultimately the hardware. I think what you see is that the numbers include core that exist physically on the die, but have been disabled during manufacturing. 
In theory toplev could renumber the core to eliminate holes, but that would be confusing because it wouldn't match any other user of core numbers.
