### ISSUE TITLE
For Skylake, the MITE and DSB formulas should be modified?

### ISSUE THREAD

**Issue by WrightChen** [andikleen/pmu-tools#172]
Hi Andi,

I noticed in the Skylake Microarchitecture, the MITE bandwidth is 5/cycle. And the DSB bandwidth is 6/cycle.

![image](https://user-images.githubusercontent.com/5458818/55624377-3aa5af00-57d8-11e9-9367-c65d2719e832.png)

But in the TMAM 3.5 "skl_client_ratios.py", the MITE and DSB formulas is below:
```
MITE.val = (EV("IDQ.ALL_MITE_CYCLES_ANY_UOPS", 3) - EV("IDQ.ALL_MITE_CYCLES_4_UOPS", 3)) / CORE_CLKS(self, EV, 3)

DSB.val = (EV("IDQ.ALL_DSB_CYCLES_ANY_UOPS", 3) - EV("IDQ.ALL_DSB_CYCLES_4_UOPS", 3)) / CORE_CLKS(self, EV, 3)
```

For the IDQ.ALL_MITE_CYCLES_4_UOPS & IDQ.ALL_DSB_CYCLES_4_UOPS events, I found they mean: 

> Counts the number of cycles 4 uops were delivered to the Instruction Decode Queue (IDQ) from the Decode Stream Buffer (DSB) path.

> Counts the number of cycles 4 uops were delivered to the Instruction Decode Queue (IDQ) from the MITE (legacy decode pipeline) path.

I think for the bandwidth bound, the DSB formula should subtract **IDQ.ALL_DSB_CYCLES_4/5/6_UOPS** from **IDQ.ALL_DSB_CYCLES_ANY_UOPS**. 
Or calculate IDQ.ALL_DSB_CYCLES_1_UOPS + IDQ.ALL_DSB_CYCLES_2_UOPS + IDQ.ALL_DSB_CYCLES_3_UOPS. 
And use that result divided by CORE_CLKS.

Same thing for the MITE bandwidth formula.

Do you think that's right? Looking forward to your reply:)

**Comment by andikleen** [comment]
How about you test if your formulas work better on some tests?

AFAIK the 5/6 cases only happen with fusion, so 4 is the full width. Ignoring that is quite reasonable, so the existing formula seems reasonable.

**Comment by travisdowns** [comment]
IMO 4 is the correct value here as Andi says.

What the diagram doesn't show is the arrow into Allocate/Rename/... only takes 4 uops. So indeed the DSB can deliver 6 uops in principle (with or without fusion): but the sustained throughput will never be > 4 - it can only deliver 6 in bursts, e.g., if the front-end get resteered due a branch misprediction, the DSB may deliver 6 per cycle for a while until the IDQ fills up. More importantly it can help achieve the max sustained of 4 in cases where deliver is sub-optimal in some cycles: e.g., if the code is aligned so that one line of the DSB only has 2 uops of a loop and the adjacent line has 6 uops, you can deliver in a 6-2-6-2 pattern, still getting to 4. If the max was 4 you'd be doing 4-2-4-2 and only average 3.
