### ISSUE TITLE
toplev: questions about the Branch.Resteers metric in toplev

### ISSUE THREAD

**Issue by StephanDollberg** [andikleen/pmu-tools#299]
Hello,

I have some questions about the Branch_Resteers metric.

First, looking at the skylake definitions for branch resteers https://github.com/andikleen/pmu-tools/blob/master/skx_server_ratios.py#L533 we see that the sample suggestion is:

```
    sample = ['BR_MISP_RETIRED.ALL_BRANCHES:pp']
```

but the actual calculation doesn't take that into account at all. Only resteer cyles and baclears:

```
            self.val = (EV("INT_MISC.CLEAR_RESTEER_CYCLES", 3) + BAClear_Cost * EV("BACLEARS.ANY", 3)) / CLKS(self, EV, 3)
```

I stumbled across this because I was using debugging something where toplev told me that branch resteering is the main issue but sampling branch-misses with perf actually claims only a small amount of branch-misses percentage wise. baclears.any is quite high though. Should the suggestion suggest all the involved metrics?

Second, looking at the haswell definitions https://github.com/andikleen/pmu-tools/blob/master/hsw_client_ratios.py#L428:

```
            self.val = BAClear_Cost *(EV("BR_MISP_RETIRED.ALL_BRANCHES", 3) + EV("MACHINE_CLEARS.COUNT", 3) + EV("BACLEARS.ANY", 3)) / CLKS(self, EV, 3)
```

We see that now BR_MISP_RETIRED.ALL_BRANCHES is at least taken into account but it's still the only suggested counter. Another thing that occurs odd to me here is that BAClear_Cost is multiplied with the whole sum and not just the BACLEARS.ANY counter as in the skylake case. Is that correct? 

Hope those questions make sense.

Cheers,
Stephan

**Comment by andikleen** [comment]
On Mon, Aug 31, 2020 at 02:56:20AM -0700, Stephan Dollberg wrote:
> Hello,
> 
> I have some questions about the Branch_Resteers metric.
> 
> First, looking at the skylake definitions for branch resteers https://
> github.com/andikleen/pmu-tools/blob/master/skx_server_ratios.py#L533 we see
> that the sample suggestion is:
> 
>     sample = ['BR_MISP_RETIRED.ALL_BRANCHES:pp']
> 
> but the actual calculation doesn't take that into account at all. Only resteer
> cyles and baclears:
> 
>             self.val = (EV("INT_MISC.CLEAR_RESTEER_CYCLES", 3) + BAClear_Cost * EV("BACLEARS.ANY", 3)) / CLKS(self, EV, 3)
> 
> I stumbled across this because I was using debugging something where toplev
> told me that branch resteering is the main issue but sampling branch-misses
> with perf actually claims only a small amount of branch-misses percentage wise.

That doesn't mean that toplev is wrong. Even a small number of
mispredicts can have a large impact. In fact it is rare to have large
number of mispredicts.

> baclears.any is quite high though. Should the suggestion suggest all the
> involved metrics?

First these are all related to branch mispredictions or effects
typically caused by mispredicts.

It is normally difficult to sample on them because branch misprediction
has a very high skid if PEBS is not used (due to it being detected very
far away from when the end of the pipeline when something can be 
sampled). So the reported IPs will not very helpful.

You could try to sample for them manually on your workload, but it's
likely it won't have good results.

That's why toplev just suggests to sample for mispredictions. There's
currently no good way to do a better sample breakdown. The break down
can only be done in counting mode.

> Second, looking at the haswell definitions https://github.com/andikleen/
> pmu-tools/blob/master/hsw_client_ratios.py#L428:
> 
>             self.val = BAClear_Cost *(EV("BR_MISP_RETIRED.ALL_BRANCHES", 3) + EV("MACHINE_CLEARS.COUNT", 3) + EV("BACLEARS.ANY", 3)) / CLKS(self, EV, 3)
> 
> We see that now BR_MISP_RETIRED.ALL_BRANCHES is at least taken into account but
> it's still the only suggested counter. Another thing that occurs odd to me here
> is that BAClear_Cost is multiplied with the whole sum and not just the
> BACLEARS.ANY counter as in the skylake case. Is that correct?

@aayasin may comment. It might be due to some workaround on Haswell.

-Andi

**Comment by aayasin** [comment]
The `Branch_Resteers` metric in TMA captures the cost of the front-end to re-fill the pipeline in light of mistakes related to branches. In the optimal case, this can cost Up to the front end Pipeline length, as Estimated by BAClear cost. 

We defer to that for typical branch mispredictions as well as machine clears, since there was no dedicated counter to measure this penalty prior to Skylake. The `INT_MISC.CLEAR_RESTEER_CYCLES` new counter measures the actual penalty for the two typical cases but not BAClear. The latter me apply for big code footprint workloads with too many branches. 

 You may read more in the [TMA paper](bit.ly/tma-ispass14).

**Comment by aayasin** [comment]
> The latter me apply for big code footprint workloads with too many branches.

me -> may

**Comment by aayasin** [comment]
By the way, I just uploaded a new kernel (micro benchmarks) for pure baclears at: https://github.com/aayasin/perf-tools/blob/master/kernels/jumpy5p14.c

**Comment by StephanDollberg** [comment]
Sorry forgot that I hadn't replied here.

Thanks guys for the quick replies, that all makes sense. Also realized that all those files are actually auto-gened from the intel definitions.
