### ISSUE TITLE
toplev chart is empty

### ISSUE THREAD

**Issue by stek79** [andikleen/pmu-tools#33]
Hi,

I have tried toplev in order to produce a chart as you show in the README.

However, I just got an empty figure (see attachment).

Command line was:

toplev.py -I 100 -l3 --title "GNU grep" --graph md5sum ~/Downloads/ubuntu-14.04.3-server-amd64.iso

![figure_1](https://cloud.githubusercontent.com/assets/15216461/10612682/27b03844-7752-11e5-974f-80b4402eef92.png)

**Comment by andikleen** [comment]
tl-barplot can only display a single CPU, but newer toplev defaults
to showing all threads on systems with SMT.

Run it with --single-thread for this case (I'll update the README), or specify the cpu
the app is executing on.  It also helps to run the workload longer and
not Ctrl-C it. The experimental browser based tl-serve is able
to display multiple CPUs.


On Tue, Oct 20, 2015 at 08:44:31AM -0700, stek79 wrote:
> Hi,
> 
> I have tried toplev in order to produce a chart as you show in the README.
> 
> However, I just got an empty figure (see attachment).
> 
> Command line was:
> 
> toplev.py -I 100 -l3 --title "GNU grep" --graph md5sum ~/Downloads/ubuntu-14.04.3-server-amd64.iso
> 
> ![figure_1](https://cloud.githubusercontent.com/assets/15216461/10612682/27b03844-7752-11e5-974f-80b4402eef92.png)
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/andikleen/pmu-tools/issues/33

-- 
ak@linux.intel.com -- Speaking for myself only.

**Comment by stefanodoni** [comment]
Hi Andy,

Thanks for the reply!

I've tried with --single-thread, but still got no meaningful results.

Here is the command line and full output I got:

$ sudo ./toplev.py -I 100 -l3 --title "GNU grep" --graph --single-thread md5sum ~/Downloads/ubuntu-14.04.3-server-amd64.iso 
PATH=$PATH:. ; tl-barplot.py --title "GNU grep"  /dev/stdin
Using level 3.
warning: removing Ports_Utilization Memory_Bound L2_Bound L1_Bound Core_Bound
due to unsupported events in kernel: CYCLE_ACTIVITY.CYCLES_NO_EXECUTE
CYCLE_ACTIVITY.STALLS_L1D_PENDING
Use --force-events to override (may result in wrong measurements)
perf stat -x\; -e 'task-clock,{cpu/event=0xc2,umask=0x2/,cpu/event=0xe,umask=0x1/,cpu/event=0xd,umask=0x3,cmask=1/,cpu/event=0x9c,umask=0x1/,cycles},{instructions,cycles,cpu/event=0x9c,umask=0x1/,cpu/event=0x9c,umask=0x1,cmask=4/},{cpu/event=0xe,umask=0x1/,cycles,cpu/event=0x79,umask=0x30/,cpu/event=0xc2,umask=0x2/},{cpu/event=0xc5,umask=0x0/,cpu/event=0xc3,umask=0x1,edge=1,cmask=1/},{cpu/event=0x80,umask=0x4/,cpu/event=0xab,umask=0x2/,cpu/event=0x87,umask=0x1/,cycles,cpu/event=0x79,umask=0x30,edge=1,cmask=1/},{cpu/event=0x14,umask=0x2/,cpu/event=0xc1,umask=0x40/,cpu/event=0xa2,umask=0x8/,cycles},{cpu/event=0x85,umask=0x60/,cpu/event=0x79,umask=0x24,cmask=4/,cycles,cpu/event=0x79,umask=0x24,cmask=1/,cpu/event=0x85,umask=0x10/},{cpu/event=0x79,umask=0x18,cmask=1/,cycles,cpu/event=0xa8,umask=0x1,cmask=4/,cpu/event=0x79,umask=0x18,cmask=4/,cpu/event=0xa8,umask=0x1,cmask=1/},{cpu/event=0xa3,umask=0x5,cmask=5/,cpu/event=0xd1,umask=0x4/,cpu/event=0xd1,umask=0x20/,cycles},{cpu/event=0x80,umask=0x4/,cpu/event=0x85,umask=0x60/,cpu/event=0x5e,umask=0x1/,cpu/event=0x85,umask=0x10/},{cpu/event=0xc5,umask=0x0/,cpu/event=0xe6,umask=0x1f/,cpu/event=0x5e,umask=0x1,edge=1,inv=1,cmask=1/,cpu/event=0xc3,umask=0x1,edge=1,cmask=1/}' -I 100 md5sum /home/ste/Downloads/ubuntu-14.04.3-server-amd64.iso
9e5fecc94b3925bededed0fdca1bd417  /home/ste/Downloads/ubuntu-14.04.3-server-amd64.iso
12 events not counted
warning: 3 division by zero errors: L3_Bound Branch_Resteers MEM_Bound
{('Backend_Bound', None): 57.41, ('CPU utilization', None): 0.84}
{('Backend_Bound', None): 56.6, ('CPU utilization', None): 0.86}
{('Backend_Bound', None): 54.73, ('CPU utilization', None): 0.82}
{('Backend_Bound', None): 57.48, ('CPU utilization', None): 0.85}
{('Backend_Bound', None): 56.4, ('CPU utilization', None): 0.77}
{('Backend_Bound', None): 57.77, ('CPU utilization', None): 0.81}
{('Backend_Bound', None): 58.76, ('CPU utilization', None): 0.78}
{('Backend_Bound', None): 59.47, ('CPU utilization', None): 0.82}
{('Backend_Bound', None): 57.12, ('CPU utilization', None): 0.82}
{('Backend_Bound', None): 59.16, ('CPU utilization', None): 0.8}
{('Backend_Bound', None): 57.8, ('CPU utilization', None): 0.84}
{('Backend_Bound', None): 58.14, ('CPU utilization', None): 0.78}
{('Backend_Bound', None): 59.14, ('CPU utilization', None): 0.77}
{('Backend_Bound', None): 58.34, ('CPU utilization', None): 0.81}
{('Backend_Bound', None): 58.79, ('CPU utilization', None): 0.8}
{('Backend_Bound', None): 59.22, ('CPU utilization', None): 2.51}

![figure_1](https://cloud.githubusercontent.com/assets/15234197/10669789/97eba2ba-78e2-11e5-90cf-3914f103bf02.png)

**Comment by andikleen** [comment]
Sorry it took so long. I fixed the plotting problems with hyperthreading now.

**Comment by stefanodoni** [comment]
Great thanks I'll try again!
